# Generated by Django 3.2.8 on 2021-11-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avm', '0005_alter_item_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_picture_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
